Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "devops-server"
  
  # Ambas configuraciones de red
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
    vb.name = "devops-ansible-server"
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "desplegar_app.yml"
    ansible.inventory_path = "inventories/vagrant/hosts.ini"
    ansible.limit = "webservers"
    ansible.verbose = "v"
  end
end